import { ServiceCategory, Professional, Address, Booking, ChatThread, AppNotification } from './types';

export const INITIAL_CATEGORIES: ServiceCategory[] = [
  {
    id: 'painter',
    name: 'Painter',
    icon: 'paint',
    tagline: 'Interior, exterior, waterproofing & stencil painting',
    startingPrice: 599,
    services: [
      { id: 'p-room', name: 'Full Room Painting', desc: 'Walls, ceiling, primer + 2 coats premium emulsion', price: 1499, duration: '1 day' },
      { id: 'p-touchup', name: 'Wall Touch-Up & Patch Repair', desc: 'Fix cracks, damp patches, peeling paint & re-coat', price: 499, duration: '2 hrs' },
      { id: 'p-waterproof', name: 'Waterproofing Treatment', desc: 'Moisture sealant coating for bathroom & balcony walls', price: 899, duration: '4 hrs' },
      { id: 'p-texture', name: 'Accent Wall & Texture Art', desc: 'Designer metallic finish or textured feature wall', price: 1999, duration: '6 hrs' },
      { id: 'p-wood', name: 'Door & Wood Polish', desc: 'Melamine or PU polish for wooden doors and frames', price: 699, duration: '3 hrs' },
    ],
  },
  {
    id: 'carpenter',
    name: 'Carpenter',
    icon: 'hammer',
    tagline: 'Furniture repair, door locks, custom woodwork & fittings',
    startingPrice: 349,
    services: [
      { id: 'c-repair', name: 'Furniture Repair', desc: 'Fix wobbly chairs, dining tables, squeaky bed frames', price: 349, duration: '1 hr' },
      { id: 'c-assembly', name: 'Bed & Wardrobe Assembly', desc: 'Precision flat-pack assembly for IKEA, Nilkamal etc.', price: 549, duration: '2 hrs' },
      { id: 'c-locks', name: 'Lock & Handle Replacement', desc: 'Smart lock, deadbolt, door hinges & handle fixing', price: 299, duration: '45 mins' },
      { id: 'c-drilling', name: 'Drilling & Wall Hanging', desc: 'Mount TV bracket, curtains, paintings & floating shelves', price: 249, duration: '45 mins' },
      { id: 'c-custom', name: 'Custom Shelves & Cabinets', desc: 'Made-to-order kitchen or study storage solutions', price: 1799, duration: '1-2 days' },
    ],
  },
  {
    id: 'plumber',
    name: 'Plumber',
    icon: 'droplet',
    tagline: 'Leak detection, tap fixtures, blocked drains & pipelines',
    startingPrice: 299,
    services: [
      { id: 'pl-leak', name: 'Water Leakage Repair', desc: 'Locate hidden leaks, seal pipe joints and valves', price: 399, duration: '1 hr' },
      { id: 'pl-tap', name: 'Tap & Shower Installation', desc: 'Fix dripping faucets or install rainfall shower heads', price: 249, duration: '45 mins' },
      { id: 'pl-drain', name: 'Drainage & Clog Clearance', desc: 'High-pressure unclogging for sinks, toilets & floor traps', price: 449, duration: '1.5 hrs' },
      { id: 'pl-geyser', name: 'Geyser / Water Heater Fitting', desc: 'Complete water inlet/outlet piping and safe mount', price: 499, duration: '1 hr' },
      { id: 'pl-tank', name: 'Overhead Tank Cleaning', desc: 'Deep mechanized cleaning and disinfectant treatment', price: 999, duration: '2.5 hrs' },
    ],
  },
  {
    id: 'electrician',
    name: 'Electrician',
    icon: 'zap',
    tagline: 'Wiring, MCB switches, fans, chandeliers & appliance setups',
    startingPrice: 299,
    services: [
      { id: 'e-fault', name: 'Short Circuit & Fault Finding', desc: 'Locate wiring faults, tripping MCBs and power drop', price: 349, duration: '1 hr' },
      { id: 'e-switch', name: 'Switchboard & Socket Replacement', desc: 'Replace burnt switch plates, modular sockets & regulators', price: 199, duration: '30 mins' },
      { id: 'e-fan', name: 'Ceiling Fan / Chandelier Install', desc: 'Balance rod, motor wiring and sturdy ceiling hookup', price: 299, duration: '45 mins' },
      { id: 'e-wiring', name: 'Room Rewiring & Inverter Setup', desc: 'Safe copper conduit wiring + battery inverter wiring', price: 899, duration: '3 hrs' },
      { id: 'e-appliance', name: 'Chimney / Microwave Wiring', desc: 'Heavy load 16A point setup with earthing check', price: 399, duration: '1 hr' },
    ],
  },
  {
    id: 'ac',
    name: 'AC Repair',
    icon: 'wrench',
    tagline: 'Split & window AC servicing, gas charging & PCB repairs',
    startingPrice: 449,
    services: [
      { id: 'ac-foam', name: 'Power Jet Foam Servicing', desc: 'Deep high-pressure coil wash, dust cleanup & tray sanitizing', price: 499, duration: '1 hr' },
      { id: 'ac-repair', name: 'Cooling Breakdown Diagnostic', desc: 'Compressor check, capacitor replacement & noise fix', price: 399, duration: '1 hr' },
      { id: 'ac-gas', name: 'Refrigerant Gas Refill', desc: 'Leak testing + complete R32/R410A gas charge', price: 1199, duration: '1.5 hrs' },
      { id: 'ac-install', name: 'AC Uninstallation & Install', desc: 'Safe copper piping mount, bracket fixture and vacuum test', price: 1299, duration: '2 hrs' },
      { id: 'ac-pcb', name: 'Inverter PCB Board Repair', desc: 'Micro-soldering, sensor replacement & voltage stabiliser check', price: 899, duration: '2 hrs' },
    ],
  },
  {
    id: 'cleaning',
    name: 'Home Cleaning',
    icon: 'sparkles',
    tagline: 'Deep home cleaning, sofa shampooing & kitchen scrubbing',
    startingPrice: 499,
    services: [
      { id: 'cl-deep', name: 'Full Home Deep Cleaning', desc: 'Scrubbing floors, degreasing kitchen, descaling bathrooms', price: 1999, duration: '4 hrs' },
      { id: 'cl-bath', name: 'Bathroom Acid & Stain Removal', desc: 'Tile grout cleaning, mirror shine, tap descaling', price: 499, duration: '1.5 hrs' },
      { id: 'cl-sofa', name: 'Sofa & Fabric Upholstery Shampoo', desc: 'Industrial suction injection & stain extraction', price: 699, duration: '2 hrs' },
      { id: 'cl-kitchen', name: 'Kitchen Chimney & Cabinet Wash', desc: 'Oil grease removal from tile backsplashes and cabinets', price: 799, duration: '2 hrs' },
    ],
  },
  {
    id: 'pest',
    name: 'Pest Control',
    icon: 'shield',
    tagline: 'Odorless cockroach gel, termite shielding & bedbug relief',
    startingPrice: 449,
    services: [
      { id: 'pc-cockroach', name: 'Cockroach & Ant Gel Treatment', desc: 'Odorless Bayer herbal gel bait across kitchen and drains', price: 499, duration: '45 mins' },
      { id: 'pc-termite', name: 'Termite Drill-Fill-Seal Control', desc: 'Woodwork injection treatment with 1-year guarantee', price: 1499, duration: '3 hrs' },
      { id: 'pc-bedbug', name: 'Bedbug Double Spray Heat Shield', desc: '2 visits thorough mattress, frame & curtain spraying', price: 899, duration: '2 hrs' },
    ],
  },
  {
    id: 'salon',
    name: 'Salon & Grooming',
    icon: 'scissors',
    tagline: 'Hygienic at-home hair styling, grooming, mani-pedi & facials',
    startingPrice: 299,
    services: [
      { id: 'sl-men', name: 'Men Haircut & Beard Grooming', desc: 'Disinfected tools, scalp massage and aftershave mist', price: 299, duration: '45 mins' },
      { id: 'sl-facial', name: 'Glow Facial & De-Tan Therapy', desc: 'Organic fruit enzymes with deep pore suction scrub', price: 649, duration: '1 hr' },
      { id: 'sl-wax', name: 'Rica Waxing & Manicure', desc: 'Gentle no-colophony wax with hand massage', price: 599, duration: '1.5 hrs' },
    ],
  },
];

export const INITIAL_PROFESSIONALS: Professional[] = [
  // Painters
  {
    id: 'pro-painter-1',
    name: 'Amit Verma',
    role: 'Master Painter & Wall Artist',
    catId: 'painter',
    rating: 4.9,
    reviewsCount: 312,
    completedJobs: 420,
    distanceKm: 1.2,
    experienceYears: 9,
    hourlyRate: 499,
    isAvailableToday: true,
    locality: 'South Extension, Delhi',
    languages: ['Hindi', 'English'],
    isVerified: true,
    responseTime: '8 min',
    bio: 'Asian Paints certified master applicator. Specialist in Royal luxury emulsion, waterproof barrier coatings, and seamless texture accent walls. Known for zero-mess tarp protection and clean edges.',
    skills: ['Interior Emulsion', 'Texture Stencil', 'PU Wood Polish', 'Damp Sealing'],
  },
  {
    id: 'pro-painter-2',
    name: 'Sunil Rathore',
    role: 'Exterior & Waterproofing Specialist',
    catId: 'painter',
    rating: 4.7,
    reviewsCount: 184,
    completedJobs: 250,
    distanceKm: 2.8,
    experienceYears: 6,
    hourlyRate: 449,
    isAvailableToday: true,
    locality: 'Saket Sector 3, Delhi',
    languages: ['Hindi'],
    isVerified: true,
    responseTime: '15 min',
    bio: 'Dedicated to durable weather-resistant paints and leak-proof primer application. Free wall moisture metering with every inspection.',
    skills: ['Weather Proofing', 'Crack Filling', 'Ceiling Primer'],
  },
  {
    id: 'pro-painter-3',
    name: 'Devendra Joshi',
    role: 'Custom Decor & Stencil Painter',
    catId: 'painter',
    rating: 4.8,
    reviewsCount: 94,
    completedJobs: 130,
    distanceKm: 3.5,
    experienceYears: 5,
    hourlyRate: 549,
    isAvailableToday: false,
    locality: 'Malviya Nagar, Delhi',
    languages: ['Hindi', 'English'],
    isVerified: true,
    responseTime: '20 min',
    bio: 'Focuses on artistic child-room stencils, metallic geometry, and high-gloss enamel door polishing.',
    skills: ['Stencil Art', 'High Gloss Enamel', 'Texture Roller'],
  },

  // Carpenters
  {
    id: 'pro-carpenter-1',
    name: 'Manoj Panchal',
    role: 'Senior Wood Artisan & Assembler',
    catId: 'carpenter',
    rating: 4.9,
    reviewsCount: 428,
    completedJobs: 560,
    distanceKm: 0.9,
    experienceYears: 12,
    hourlyRate: 349,
    isAvailableToday: true,
    locality: 'Hauz Khas, Delhi',
    languages: ['Hindi', 'Punjabi'],
    isVerified: true,
    responseTime: '5 min',
    bio: 'Specialist in custom modular repairs, hydraulic hinges, channel drawers, and quick IKEA / Urban Ladder furniture assembly. Arrives equipped with laser levels and silent cordless power tools.',
    skills: ['Modular Fittings', 'Hydraulic Bed Lifts', 'Smart Lock Fitting', 'Laminate Work'],
  },
  {
    id: 'pro-carpenter-2',
    name: 'Rajesh Sharma',
    role: 'Door, Lock & Cabinet Expert',
    catId: 'carpenter',
    rating: 4.6,
    reviewsCount: 165,
    completedJobs: 210,
    distanceKm: 2.1,
    experienceYears: 7,
    hourlyRate: 299,
    isAvailableToday: true,
    locality: 'Kalkaji, Delhi',
    languages: ['Hindi', 'English'],
    isVerified: true,
    responseTime: '12 min',
    bio: 'Quick fixes for sticking doors, broken hinges, sliding closet rollers, and antique furniture preservation.',
    skills: ['Door Planing', 'Lock Replacement', 'Sliding Wardrobes'],
  },

  // Plumbers
  {
    id: 'pro-plumber-1',
    name: 'Sanjay Yadav',
    role: 'Master Plumber & Pipeline Engineer',
    catId: 'plumber',
    rating: 4.8,
    reviewsCount: 520,
    completedJobs: 710,
    distanceKm: 1.4,
    experienceYears: 11,
    hourlyRate: 299,
    isAvailableToday: true,
    locality: 'Green Park, Delhi',
    languages: ['Hindi', 'English'],
    isVerified: true,
    responseTime: '6 min',
    bio: 'Certified by Indian Plumbing Skill Council. Fast response for emergency water bursts, diverter repairs, pressure pump setups, and stubborn bathroom drain clearing.',
    skills: ['Concealed Diverters', 'Jet Unclogging', 'Pressure Pumps', 'CPVC Jointing'],
  },
  {
    id: 'pro-plumber-2',
    name: 'Imran Ali',
    role: 'Bathroom Sanitary & Fixture Pro',
    catId: 'plumber',
    rating: 4.7,
    reviewsCount: 230,
    completedJobs: 340,
    distanceKm: 2.6,
    experienceYears: 8,
    hourlyRate: 349,
    isAvailableToday: false,
    locality: 'Lajpat Nagar IV, Delhi',
    languages: ['Hindi', 'Urdu'],
    isVerified: true,
    responseTime: '18 min',
    bio: 'Expert installer for Grohe, Kohler and Jaquar bath systems. Precise leak tracking with minimal wall damage.',
    skills: ['Jaquar/Kohler Fittings', 'Wall Hung Toilets', 'Geyser Piping'],
  },

  // Electricians
  {
    id: 'pro-electrician-1',
    name: 'Vikram Singh',
    role: 'Licensed Master Electrician',
    catId: 'electrician',
    rating: 4.9,
    reviewsCount: 610,
    completedJobs: 890,
    distanceKm: 0.8,
    experienceYears: 10,
    hourlyRate: 299,
    isAvailableToday: true,
    locality: 'Greater Kailash 1, Delhi',
    languages: ['Hindi', 'English'],
    isVerified: true,
    responseTime: '4 min',
    bio: 'Govt. Grade-A licensed electrical wireman. Known for meticulous wire management, resolving tripping breakers, invertor rewiring, and surge protection installations.',
    skills: ['Tripping Diagnostic', 'MCB Distribution Box', 'Heavy Inverter Wiring', 'Earthing Checks'],
  },
  {
    id: 'pro-electrician-2',
    name: 'Karan Mehra',
    role: 'Lighting & Smart Home Electrician',
    catId: 'electrician',
    rating: 4.8,
    reviewsCount: 145,
    completedJobs: 190,
    distanceKm: 3.1,
    experienceYears: 5,
    hourlyRate: 349,
    isAvailableToday: true,
    locality: 'Panchsheel Park, Delhi',
    languages: ['Hindi', 'English'],
    isVerified: true,
    responseTime: '10 min',
    bio: 'Experienced in warm architectural cove lighting, smart WiFi switches, designer pendant ceiling lights, and home theatre cabling.',
    skills: ['Smart Switches', 'Cove Strip Lights', 'Chandelier Mounting'],
  },

  // AC Technicians
  {
    id: 'pro-ac-1',
    name: 'Rahul Kumar',
    role: 'HVAC Specialist & Inverter AC Tech',
    catId: 'ac',
    rating: 4.9,
    reviewsCount: 780,
    completedJobs: 1100,
    distanceKm: 1.1,
    experienceYears: 9,
    hourlyRate: 499,
    isAvailableToday: true,
    locality: 'Saket, Delhi',
    languages: ['Hindi', 'English'],
    isVerified: true,
    responseTime: '7 min',
    bio: 'Former Daikin & Voltas authorized senior engineer. Equipped with pressure foam jets, digital manifold gauges, and genuine OEM capacitors. Guarantees 30-day cooling assurance.',
    skills: ['Foam Jet Servicing', 'R32 Gas Charging', 'Inverter PCB Fixes', 'Copper Flare Jointing'],
  },
  {
    id: 'pro-ac-2',
    name: 'Deepak Tyagi',
    role: 'Dual Inverter & Commercial AC Tech',
    catId: 'ac',
    rating: 4.7,
    reviewsCount: 310,
    completedJobs: 430,
    distanceKm: 2.4,
    experienceYears: 7,
    hourlyRate: 449,
    isAvailableToday: true,
    locality: 'Malviya Nagar, Delhi',
    languages: ['Hindi'],
    isVerified: true,
    responseTime: '14 min',
    bio: 'Fast resolution for ice freeze issues, noisy fan blowers, and water leakage inside bedroom units.',
    skills: ['Water Leak Drip Fix', 'Blower Motor Swap', 'Gas Top-Up'],
  },

  // Cleaning
  {
    id: 'pro-cleaning-1',
    name: 'Pooja & Team Shines',
    role: 'Sanitization & Deep Cleaning Crew',
    catId: 'cleaning',
    rating: 4.9,
    reviewsCount: 290,
    completedJobs: 380,
    distanceKm: 1.8,
    experienceYears: 6,
    hourlyRate: 599,
    isAvailableToday: true,
    locality: 'Chittaranjan Park, Delhi',
    languages: ['Hindi', 'Bengali'],
    isVerified: true,
    responseTime: '12 min',
    bio: 'Uses Kärcher single-disc scrubbing machines and Diversey eco-friendly chemical disinfectants for spotless kitchens and sparkling tile floors.',
    skills: ['Machine Scrubbing', 'Degreasing', 'Sanitization'],
  },
];

export const INITIAL_ADDRESSES: Address[] = [
  {
    id: 'addr-home',
    label: 'Home',
    type: 'home',
    line1: 'Flat 402, Block B, Silver Oak Residency, Saket',
    city: 'New Delhi',
    pincode: '110017',
    isDefault: true,
  },
  {
    id: 'addr-work',
    label: 'Office Studio',
    type: 'work',
    line1: 'Suite 204, Sector 44, Near Huda City Metro',
    city: 'Gurugram',
    pincode: '122003',
  },
  {
    id: 'addr-parents',
    label: "Parents' House",
    type: 'other',
    line1: 'C-14, DDA Flats, Kalkaji Extn',
    city: 'New Delhi',
    pincode: '110019',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'OC-94821',
    catId: 'painter',
    serviceId: 'p-room',
    serviceName: 'Full Room Painting',
    proId: 'pro-painter-1',
    proName: 'Amit Verma',
    proRole: 'Master Painter & Wall Artist',
    date: 'Tomorrow, Oct 9',
    timeSlot: '10:00 AM',
    address: INITIAL_ADDRESSES[0],
    status: 'confirmed',
    price: 1499,
    platformFee: 20,
    paymentMethod: 'upi',
    createdAt: 'Today, 02:40 PM',
    timelineStep: 1, // assigned
  },
  {
    id: 'OC-93104',
    catId: 'ac',
    serviceId: 'ac-foam',
    serviceName: 'Power Jet Foam Servicing',
    proId: 'pro-ac-1',
    proName: 'Rahul Kumar',
    proRole: 'HVAC Specialist',
    date: 'Today, Oct 8',
    timeSlot: '04:00 PM',
    address: INITIAL_ADDRESSES[0],
    status: 'in_progress',
    price: 499,
    platformFee: 20,
    paymentMethod: 'upi',
    createdAt: 'Today, 11:15 AM',
    timelineStep: 3, // arrived & working
  },
  {
    id: 'OC-91028',
    catId: 'plumber',
    serviceId: 'pl-leak',
    serviceName: 'Water Leakage Repair',
    proId: 'pro-plumber-1',
    proName: 'Sanjay Yadav',
    proRole: 'Master Plumber',
    date: '3 Oct 2026',
    timeSlot: '02:00 PM',
    address: INITIAL_ADDRESSES[0],
    status: 'completed',
    price: 399,
    platformFee: 20,
    paymentMethod: 'cash',
    createdAt: '3 Oct 2026',
    ratingGiven: 5,
    reviewNote: 'Arrived within 20 mins, fixed pipe joint neatly. Highly recommended!',
    timelineStep: 5,
  },
  {
    id: 'OC-89412',
    catId: 'carpenter',
    serviceId: 'c-locks',
    serviceName: 'Lock & Handle Replacement',
    proId: 'pro-carpenter-1',
    proName: 'Manoj Panchal',
    proRole: 'Senior Wood Artisan',
    date: '28 Sep 2026',
    timeSlot: '11:00 AM',
    address: INITIAL_ADDRESSES[1],
    status: 'completed',
    price: 299,
    platformFee: 20,
    paymentMethod: 'card',
    createdAt: '28 Sep 2026',
    ratingGiven: 5,
    reviewNote: 'Replaced deadbolt lock effortlessly. Very polite professional.',
    timelineStep: 5,
  },
  {
    id: 'OC-88201',
    catId: 'electrician',
    serviceId: 'e-switch',
    serviceName: 'Switchboard Replacement',
    proId: 'pro-electrician-1',
    proName: 'Vikram Singh',
    proRole: 'Licensed Master Electrician',
    date: '19 Sep 2026',
    timeSlot: '03:30 PM',
    address: INITIAL_ADDRESSES[0],
    status: 'cancelled',
    price: 199,
    platformFee: 20,
    paymentMethod: 'upi',
    createdAt: '19 Sep 2026',
    timelineStep: 0,
  },
];

export const INITIAL_CHATS: ChatThread[] = [
  {
    proId: 'pro-painter-1',
    proName: 'Amit Verma',
    proRole: 'Master Painter',
    lastMessage: 'I have packed the primer and drop cloths. Will reach by 10 AM sharp tomorrow.',
    lastTime: '12:30 PM',
    unreadCount: 1,
    messages: [
      { id: 'm1', sender: 'user', text: 'Hi Amit, will you be bringing wall masking sheets to cover the TV?', timestamp: '12:15 PM' },
      { id: 'm2', sender: 'pro', text: 'Yes absolutely! We bring heavy waterproof plastic sheets for all furniture and electronics.', timestamp: '12:22 PM' },
      { id: 'm3', sender: 'pro', text: 'I have packed the primer and drop cloths. Will reach by 10 AM sharp tomorrow.', timestamp: '12:30 PM' },
    ],
  },
  {
    proId: 'pro-ac-1',
    proName: 'Rahul Kumar',
    proRole: 'HVAC Specialist',
    lastMessage: 'I am on my scooter heading your way. ETA 15 mins.',
    lastTime: '03:42 PM',
    unreadCount: 0,
    messages: [
      { id: 'm10', sender: 'pro', text: 'Hello! I am assigned for your AC Foam Jet service at 4 PM.', timestamp: '03:10 PM' },
      { id: 'm11', sender: 'user', text: 'Great, please call when you reach the security gate.', timestamp: '03:12 PM' },
      { id: 'm12', sender: 'pro', text: 'I am on my scooter heading your way. ETA 15 mins.', timestamp: '03:42 PM' },
    ],
  },
  {
    proId: 'pro-plumber-1',
    proName: 'Sanjay Yadav',
    proRole: 'Master Plumber',
    lastMessage: 'Glad everything is working without any leaks! Have a great week.',
    lastTime: '3 Oct',
    unreadCount: 0,
    messages: [
      { id: 'm20', sender: 'pro', text: 'Done with the CPVC connector replacement.', timestamp: '02:45 PM' },
      { id: 'm21', sender: 'user', text: 'Thank you Sanjay, tested the main valve and no drips!', timestamp: '02:50 PM' },
      { id: 'm22', sender: 'pro', text: 'Glad everything is working without any leaks! Have a great week.', timestamp: '02:52 PM' },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'AC Technician on the way',
    description: 'Rahul Kumar is en route to Flat 402, Saket. ETA is ~15 minutes.',
    timestamp: '15 mins ago',
    read: false,
    type: 'booking',
  },
  {
    id: 'notif-2',
    title: 'Full Room Painting Scheduled',
    description: 'Amit Verma confirmed your appointment for tomorrow, 10:00 AM.',
    timestamp: '3 hrs ago',
    read: false,
    type: 'booking',
  },
  {
    id: 'notif-3',
    title: 'Festival Home Glow Offer',
    description: 'Enjoy ₹100 off on Interior Painting & Deep Cleaning bookings with code FESTIVE.',
    timestamp: '1 day ago',
    read: true,
    type: 'alert',
  },
  {
    id: 'notif-4',
    title: 'Plumbing Service Completed',
    description: 'Receipt generated for ₹399. Download invoice from your Bookings tab.',
    timestamp: '5 days ago',
    read: true,
    type: 'booking',
  },
];
